names:
- 케일_생육기_잎
- 케일_생육기_주
- 케일_정식기_잎
- 케일_정식기_주
- 케일_수확기_주
- 케일_수확기_잎
- 케일_생육기_줄기
- 케일_생육기_과실
- 상추_정식기_주
- 상추_정식기_잎
- 상추_생육기_주
- 상추_생육기_잎
- 상추_생육기_줄기
- 상추_수확기_잎
- 상추_수확기_주
- 상추_생육기_과실
- 상추_정식기_줄기
- 근대_정식기_잎
- 근대_정식기_주
- 근대_생육기_잎
- 근대_생육기_주
- 근대_수확기_잎
- 근대_수확기_주
- 근대_생육기_과실
- 근대_정식기_줄기
- 근대_생육기_줄기
- 겨자채_정식기_주
- 겨자채_정식기_잎
- 겨자채_생육기_잎
- 겨자채_생육기_주
- 겨자채_수확기_잎
- 겨자채_수확기_주
- 겨자채_정식기_줄기
- 겨자채_수확기_과실
- 겨자채_생육기_과실
- 겨자채_생육기_줄기
- 겨자채_생육기_화방

nc: 37
test: C:/Users/kiusw/Desktop/smart/AI_YOLO/test/images
train: C:/Users/kiusw/Desktop/smart/AI_YOLO/train/images
val: C:/Users/kiusw/Desktop/smart/AI_YOLO/val/images